name: pdf_magic_mobile
description: Mobile and portable Flutter frontend for PDF Magic.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  file_picker: ^13.1.0
  flutter:
    sdk: flutter
  pdfrx: ^2.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
